// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    FaSolidLessThan: typeof import('~icons/fa-solid/less-than')['default']
    FluentQuestion48Filled: typeof import('~icons/fluent/question48-filled')['default']
    FontelicoEmoSunglasses: typeof import('~icons/fontelico/emo-sunglasses')['default']
    FontistoLinkedin: typeof import('~icons/fontisto/linkedin')['default']
    Footer: typeof import('./global/components/Footer.vue')['default']
    IonMdHeart: typeof import('~icons/ion/md-heart')['default']
    UilExternalLinkAlt: typeof import('~icons/uil/external-link-alt')['default']
    WhhHandswipe: typeof import('~icons/whh/handswipe')['default']
    ZmdiGithubAlt: typeof import('~icons/zmdi/github-alt')['default']
  }
}

export { }
