// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FontelicoEmoSunglasses: typeof import('~icons/fontelico/emo-sunglasses')['default']
    Footer: typeof import('./global/components/Footer.vue')['default']
    UilExternalLinkAlt: typeof import('~icons/uil/external-link-alt')['default']
  }
}

export { }
