import type { Dictionary, NameList } from '@ROOT/src/types'
// CONSTANTS

export const APOSTROPHE_CHAR = "'"
export const DASH_CHAR = '-'
export const EMPTY_CHAR = ''

export const GENDERS: Dictionary<string> = {
  Female: 'Femme',
  Male: 'Homme',
  Neuter: 'Neutre',
}
export const AGGLOMERATIONS: Dictionary<string> = {
  City: 'Ville',
  Town: 'Village',
}

export type SpecialCharSpecs = Dictionary<Dictionary<any>>

const DEFAULT_SPECIAL_CHARS: SpecialCharSpecs = {
  [APOSTROPHE_CHAR]: {
    isException: (/* name, charIndex */) => false,
    minDistFromEdges: 1, // 0 = first/last char
    maxAllowed: 1,
  },
  [DASH_CHAR]: { isException: (/* name, charIndex */) => false, minDistFromEdges: 3, maxAllowed: 1 },
}

// FUNCTIONS

const getNameSizeLimits = (nameList: NameList, PopulationName: string) => {
  const output = {
    minSize: 0,
    maxSize: 0,
  }
  if (!nameList.length) {
    return output
  }
  output.minSize = nameList[0].length
  output.maxSize = nameList[0].length
  nameList.forEach((name) => {
    if (name.length < output.minSize) {
      output.minSize = name.length
    }
    if (name.length > output.maxSize) {
      output.maxSize = name.length
    }
  })
  // manual override
  switch (PopulationName) {
    case 'Atlec':
      output.minSize = 6
      break
    case 'Zacoalt':
      output.minSize = 5
      break
    case 'Akoutlal':
      output.minSize = 4
      break
    case 'Oxotlli':
      output.minSize = 5
      break
    case 'Cutchakan&Iktomi':
      output.minSize = 5
      break
    default:
      break
  }
  return output
}

const objectDeepEnoughCopy = (obj: object) =>
  Object.fromEntries(
    Object.entries(obj).reduce((acc: any[], curr) => {
      acc.push([curr[0], { ...curr[1] }])
      return acc
    }, [])
  )

// DATA
declare type PopulationName = Array<{ gender: string; name: string }>
export type RedirectionLinks = { population: string | string[]; info?: boolean }
export type PopulationData = {
  agglomerationTemplates: Dictionary<(n: string) => string>
  criteria: Dictionary<Array<string>>
  names: PopulationName
  nomenclature: { nameSize: { min: number; max: number }; specialChars: SpecialCharSpecs }
  redirectionLinks: RedirectionLinks
}

const rawPopulationBase: Dictionary<PopulationData> = {
  Zacoalt: {
    agglomerationTemplates: {
      City: (n: string) => `${n}'tlan`,
      Town: (n: string) => `${n}'te`,
    },
    criteria: {
      gender: ['Male', 'Female'],
      agglomeration: Object.keys(AGGLOMERATIONS),
    },
    get names() {
      const gender = Object.fromEntries(Object.entries(GENDERS).filter(([k]) => this.criteria.gender.includes(k)))
      return [
        { gender: gender.Female, name: 'Tutchacali' },
        { gender: gender.Female, name: 'Aitzi-tli' },
        { gender: gender.Female, name: 'Macoalt' },
        { gender: gender.Female, name: 'Pacoa' },
        { gender: gender.Female, name: 'Cuaxa' },
        { gender: gender.Female, name: 'Li-tatli' },
        { gender: gender.Female, name: 'Akatchuya' },
        { gender: gender.Female, name: 'Yaxoatli' },
        { gender: gender.Female, name: 'Ilxi' },
        { gender: gender.Female, name: 'Macaxa' },
        { gender: gender.Female, name: 'Linka' },
        { gender: gender.Female, name: 'Atawalaxt' },
        { gender: gender.Female, name: 'Tlaloli' },
        { gender: gender.Female, name: 'Citli' },
        { gender: gender.Female, name: 'Cocata' },
        { gender: gender.Female, name: 'Manaui' },
        { gender: gender.Female, name: 'Teoxixi' },
        { gender: gender.Female, name: 'Patatli' },
        { gender: gender.Female, name: 'Amalinpi' },
        { gender: gender.Female, name: 'Mictatli' },
        { gender: gender.Female, name: 'Texitli' },
        { gender: gender.Female, name: 'Apali' },
        { gender: gender.Female, name: 'Zycanta' },
        { gender: gender.Female, name: 'Titli' },
        { gender: gender.Female, name: 'Eloxitli' },
        { gender: gender.Female, name: 'Huemaxt' },
        { gender: gender.Female, name: 'Chalicta' },
        { gender: gender.Female, name: 'Cicatel' },
        { gender: gender.Female, name: 'Temara' },
        { gender: gender.Female, name: 'Quautecol' },
        { gender: gender.Female, name: 'Chelatli' },
        { gender: gender.Female, name: 'Ipalli' },
        { gender: gender.Female, name: 'Itemoca' },
        { gender: gender.Female, name: 'Momaxtal' },
        { gender: gender.Female, name: 'Tlatemacoli' },
        { gender: gender.Female, name: 'Mezahua' },
        { gender: gender.Female, name: 'Ximapotla' },
        { gender: gender.Female, name: 'Tepa' },
        { gender: gender.Female, name: 'Ilcotatl' },
        { gender: gender.Female, name: 'Patlicta' },
        { gender: gender.Female, name: 'Zoyoli' },
        { gender: gender.Female, name: 'Camaxta' },
        { gender: gender.Female, name: 'Nemacol' },
        { gender: gender.Female, name: 'Zotelitli' },
        { gender: gender.Female, name: 'Cozacahui' },
        { gender: gender.Female, name: 'Cucaya' },
        { gender: gender.Female, name: 'Xochica' },
        { gender: gender.Female, name: 'Zumacol' },
        { gender: gender.Female, name: 'Mamaxel' },
        { gender: gender.Female, name: 'Mazacaxtli' },
        { gender: gender.Female, name: 'Tochetli' },
        { gender: gender.Female, name: 'Awapocutli' },
        { gender: gender.Female, name: 'Cuepilitli' },
        { gender: gender.Female, name: 'Tatzatli' },
        { gender: gender.Female, name: 'Yolotzina' },
        { gender: gender.Female, name: 'Xonaltla' },
        { gender: gender.Female, name: 'Imalma' },
        { gender: gender.Female, name: 'Xicuetli' },
        { gender: gender.Female, name: 'Chalxihuitli' },
        { gender: gender.Female, name: 'Izipacel' },
        { gender: gender.Female, name: 'Ixicamitli' },
        { gender: gender.Male, name: 'Cuat-otl' },
        { gender: gender.Male, name: 'Tliloc' },
        { gender: gender.Male, name: 'Quet-Icu' },
        { gender: gender.Male, name: 'Xotelc' },
        { gender: gender.Male, name: 'Pillomoc' },
        { gender: gender.Male, name: 'Mekticol' },
        { gender: gender.Male, name: 'Xotelc' },
        { gender: gender.Male, name: 'Zimacoat' },
        { gender: gender.Male, name: 'Mahual' },
        { gender: gender.Male, name: 'Ziteloc' },
        { gender: gender.Male, name: 'Patsacl' },
        { gender: gender.Male, name: 'Cchiczalt' },
        { gender: gender.Male, name: 'Coatlac' },
        { gender: gender.Male, name: 'Mokteza' },
        { gender: gender.Male, name: 'Coyotel' },
        { gender: gender.Male, name: 'Telitzal' },
        { gender: gender.Male, name: 'Xochitl' },
        { gender: gender.Male, name: 'Ixtlilotl' },
        { gender: gender.Male, name: 'Canachitl' },
        { gender: gender.Male, name: 'Itope' },
        { gender: gender.Male, name: 'Ipal' },
        { gender: gender.Male, name: 'Eloxocatal' },
        { gender: gender.Male, name: 'Tole' },
        { gender: gender.Male, name: 'yolote' },
        { gender: gender.Male, name: 'Xocatl' },
        { gender: gender.Male, name: 'Xipil' },
        { gender: gender.Male, name: 'Itle' },
        { gender: gender.Male, name: 'Achcatel' },
        { gender: gender.Male, name: 'Moxtel' },
        { gender: gender.Male, name: 'Tezacaco' },
        { gender: gender.Male, name: 'Ecapan' },
        { gender: gender.Male, name: 'Xocoyo' },
        { gender: gender.Male, name: 'Ezahuitl' },
        { gender: gender.Male, name: 'Mazatan' },
        { gender: gender.Male, name: 'Chimelpoca' },
        { gender: gender.Male, name: 'Tenoch' },
        { gender: gender.Male, name: 'Chical' },
        { gender: gender.Male, name: 'Tozapetecl' },
        { gender: gender.Male, name: 'Pilocotlal' },
        { gender: gender.Male, name: 'Ollope' },
        { gender: gender.Male, name: 'Tlalcapo' },
        { gender: gender.Male, name: 'Cahelel' },
        { gender: gender.Male, name: 'Ahuapilante' },
        { gender: gender.Male, name: 'Necayotl' },
        { gender: gender.Male, name: 'Namape' },
        { gender: gender.Male, name: 'Neznite' },
        { gender: gender.Male, name: 'Oltezocl' },
        { gender: gender.Male, name: 'Ilcapal' },
        { gender: gender.Male, name: 'Xiolico' },
        { gender: gender.Male, name: 'Tezocometl' },
        { gender: gender.Male, name: 'Ayalpopocol' },
        { gender: gender.Male, name: 'Axayacetl' },
        { gender: gender.Male, name: 'Toticue' },
        { gender: gender.Male, name: 'Macachital' },
        { gender: gender.Male, name: 'Necometl' },
        { gender: gender.Male, name: 'Sacotonal' },
        { gender: gender.Male, name: 'Tlacotal' },
        { gender: gender.Male, name: 'Ciquetzal' },
        { gender: gender.Male, name: 'Tlacotchitle' },
        { gender: gender.Male, name: 'Caxochiqetec' },
        { gender: gender.Male, name: 'Yozopan' },
      ]
    },
    get nomenclature() {
      const { minSize, maxSize } = getNameSizeLimits(
        this.names.reduce((acc: string[], curr: Dictionary<string>) => {
          acc.push(curr.name)
          return acc
        }, []),
        'Zacoalt'
      )
      return {
        nameSize: { min: minSize, max: maxSize },
        specialChars: DEFAULT_SPECIAL_CHARS,
      }
    },
    redirectionLinks: {
      population: 'https://catchaluk.wixsite.com/lejdr/les-zacoalts',
    },
  },
  Atlec: {
    agglomerationTemplates: {
      City: (n: string) => `${n}'uechan`,
      Town: (n: string) => `${n}'uche`,
    },
    criteria: {
      gender: ['Male', 'Female', 'Neuter'],
      agglomeration: Object.keys(AGGLOMERATIONS),
    },
    get names() {
      const gender = Object.fromEntries(Object.entries(GENDERS).filter(([k]) => this.criteria.gender.includes(k)))
      return [
        { gender: gender.Female, name: 'Wamani' },
        { gender: gender.Female, name: 'Koyara' },
        { gender: gender.Female, name: 'Qispi' },
        { gender: gender.Female, name: 'Urupi' },
        { gender: gender.Female, name: 'Nusta' },
        { gender: gender.Female, name: 'Palanti' },
        { gender: gender.Female, name: 'Killa' },
        { gender: gender.Female, name: 'Coyami' },
        { gender: gender.Female, name: 'Mapanina' },
        { gender: gender.Female, name: 'Amanta' },
        { gender: gender.Female, name: 'Kusinia' },
        { gender: gender.Female, name: 'Matchana' },
        { gender: gender.Female, name: 'Atisi' },
        { gender: gender.Female, name: 'Patcharimi' },
        { gender: gender.Female, name: 'Hamuti' },
        { gender: gender.Female, name: 'Uchica' },
        { gender: gender.Female, name: 'Ulikisaka' },
        { gender: gender.Female, name: 'Nullaya' },
        { gender: gender.Female, name: 'Kapari' },
        { gender: gender.Female, name: 'Atipusca' },
        { gender: gender.Female, name: 'Unia' },
        { gender: gender.Female, name: 'Sanca' },
        { gender: gender.Female, name: 'Callilcani' },
        { gender: gender.Female, name: 'Allinchi' },
        { gender: gender.Female, name: 'Yayasi' },
        { gender: gender.Female, name: 'Mikilla' },
        { gender: gender.Female, name: 'Muniti' },
        { gender: gender.Female, name: 'Awatinka' },
        { gender: gender.Female, name: 'Rinra' },
        { gender: gender.Female, name: 'Uilla' },
        { gender: gender.Female, name: 'Cayani' },
        { gender: gender.Female, name: 'Casayisicha' },
        { gender: gender.Female, name: 'Cucuiska' },
        { gender: gender.Female, name: 'Guacamayi' },
        { gender: gender.Female, name: 'Runicha' },
        { gender: gender.Female, name: 'Kachilla' },
        { gender: gender.Female, name: 'Matachini' },
        { gender: gender.Female, name: 'Puni' },
        { gender: gender.Female, name: 'Yarariki' },
        { gender: gender.Female, name: 'Rakimi' },
        { gender: gender.Female, name: 'Collki' },
        { gender: gender.Female, name: 'Callicha' },
        { gender: gender.Female, name: 'Icha' },
        { gender: gender.Female, name: 'Uihuaska' },
        { gender: gender.Female, name: 'Camity' },
        { gender: gender.Female, name: 'Pahuani' },
        { gender: gender.Female, name: 'Allisi' },
        { gender: gender.Female, name: 'Ucuri' },
        { gender: gender.Female, name: 'Ticuna' },
        { gender: gender.Female, name: 'Huayachi' },
        { gender: gender.Female, name: 'Cayanami' },
        { gender: gender.Female, name: 'Maycacuni' },
        { gender: gender.Female, name: 'Mayumani' },
        { gender: gender.Female, name: 'Pomawari' },
        { gender: gender.Female, name: 'Kaykusi' },
        { gender: gender.Female, name: 'Niniwana' },
        { gender: gender.Female, name: 'Pillcomayca' },
        { gender: gender.Female, name: 'Rumamaki' },
        { gender: gender.Female, name: 'Ulla' },
        { gender: gender.Female, name: 'Chambika' },
        { gender: gender.Female, name: 'Maripi' },
        { gender: gender.Male, name: 'Chicha-be' },
        { gender: gender.Male, name: 'Uchutay' },
        { gender: gender.Male, name: 'Mokatche' },
        { gender: gender.Male, name: 'Urco' },
        { gender: gender.Male, name: 'Achi-be' },
        { gender: gender.Male, name: 'Kuntor' },
        { gender: gender.Male, name: 'Mallco' },
        { gender: gender.Male, name: 'Rupon' },
        { gender: gender.Male, name: 'Ollanto' },
        { gender: gender.Male, name: 'Otoro' },
        { gender: gender.Male, name: 'Otchikon' },
        { gender: gender.Male, name: 'Oco' },
        { gender: gender.Male, name: 'Atiquo' },
        { gender: gender.Male, name: 'Kori-be' },
        { gender: gender.Male, name: 'Viraquo' },
        { gender: gender.Male, name: 'Payauanto' },
        { gender: gender.Male, name: 'Achakuykon' },
        { gender: gender.Male, name: 'Palluchon' },
        { gender: gender.Male, name: 'Cachi-be' },
        { gender: gender.Male, name: 'Huonchoc' },
        { gender: gender.Male, name: 'Cochatay' },
        { gender: gender.Male, name: 'Yancapon' },
        { gender: gender.Male, name: 'Yapon' },
        { gender: gender.Male, name: 'Napunko-be' },
        { gender: gender.Male, name: 'Achamayon' },
        { gender: gender.Male, name: 'Caskuyo' },
        { gender: gender.Male, name: 'Pasoyo' },
        { gender: gender.Male, name: 'Muntay' },
        { gender: gender.Male, name: 'Pochincho' },
        { gender: gender.Male, name: 'Huata-be' },
        { gender: gender.Male, name: 'Pampacharo' },
        { gender: gender.Male, name: 'Incollko' },
        { gender: gender.Male, name: 'Hulliarakon' },
        { gender: gender.Male, name: 'Cachako' },
        { gender: gender.Male, name: 'Kuolco' },
        { gender: gender.Male, name: 'Kulla-be' },
        { gender: gender.Male, name: 'Ikon' },
        { gender: gender.Male, name: 'Mancuyon' },
        { gender: gender.Male, name: 'Huamayoc' },
        { gender: gender.Male, name: 'Panpe' },
        { gender: gender.Male, name: 'Kita-be' },
        { gender: gender.Male, name: 'Chakayon' },
        { gender: gender.Male, name: 'Macancayo' },
        { gender: gender.Male, name: 'Awachukon' },
        { gender: gender.Male, name: 'Patsakuyo' },
        { gender: gender.Male, name: 'Uyoco' },
        { gender: gender.Male, name: 'Yacuton' },
        { gender: gender.Male, name: 'Kakayo' },
        { gender: gender.Male, name: 'Humayo' },
        { gender: gender.Male, name: 'Cullullaicay' },
        { gender: gender.Male, name: 'Wakantor' },
        { gender: gender.Male, name: 'Huacascay' },
        { gender: gender.Male, name: 'Qurallamo' },
        { gender: gender.Male, name: 'Haskuconpor' },
        { gender: gender.Male, name: 'Kuoqilcon' },
        { gender: gender.Male, name: 'Vicamoktan' },
        { gender: gender.Male, name: 'Chokopan' },
        { gender: gender.Male, name: 'Huapokoncoc' },
        { gender: gender.Male, name: 'Sayripo' },
        { gender: gender.Male, name: 'Pillihuaman' },
        { gender: gender.Male, name: 'Cahuaninpan' },
        { gender: gender.Neuter, name: 'Siku' },
        { gender: gender.Neuter, name: 'Yuyay' },
        { gender: gender.Neuter, name: 'Cumi' },
        { gender: gender.Neuter, name: 'Churusu' },
        { gender: gender.Neuter, name: 'Picu' },
        { gender: gender.Neuter, name: 'Apay' },
        { gender: gender.Neuter, name: 'Hupampu' },
        { gender: gender.Neuter, name: 'Huasaricu' },
        { gender: gender.Neuter, name: 'Caycu' },
        { gender: gender.Neuter, name: 'Cukil' },
        { gender: gender.Neuter, name: 'Puchasku' },
        { gender: gender.Neuter, name: 'Uyutin' },
        { gender: gender.Neuter, name: 'Pacuncu' },
        { gender: gender.Neuter, name: 'Tonikance' },
        { gender: gender.Neuter, name: 'Quappay' },
        { gender: gender.Neuter, name: 'Matuctu' },
        { gender: gender.Neuter, name: 'Chuyocochu' },
        { gender: gender.Neuter, name: 'Chuyacu' },
        { gender: gender.Neuter, name: 'Kiskil' },
        { gender: gender.Neuter, name: 'Kuyultil' },
        { gender: gender.Neuter, name: 'Tokyascu' },
        { gender: gender.Neuter, name: 'Ucharakil' },
        { gender: gender.Neuter, name: 'Pampay' },
        { gender: gender.Neuter, name: 'Inincanchiku' },
        { gender: gender.Neuter, name: 'Atsakay' },
        { gender: gender.Neuter, name: 'Anku' },
        { gender: gender.Neuter, name: 'Huaranku' },
        { gender: gender.Neuter, name: 'Yanansaku' },
        { gender: gender.Neuter, name: 'Chichinku' },
        { gender: gender.Neuter, name: 'Ripil' },
        { gender: gender.Neuter, name: 'Huapantay' },
        { gender: gender.Neuter, name: 'Cokchaku' },
        { gender: gender.Neuter, name: 'Sisillcay' },
        { gender: gender.Neuter, name: 'Payu' },
        { gender: gender.Neuter, name: 'Tupil' },
        { gender: gender.Neuter, name: 'Kukunay' },
        { gender: gender.Neuter, name: 'Urupil' },
        { gender: gender.Neuter, name: 'Pawatintu' },
        { gender: gender.Neuter, name: 'Churikachu' },
        { gender: gender.Neuter, name: 'Chapil' },
        { gender: gender.Neuter, name: 'Apachu' },
        { gender: gender.Neuter, name: 'Yamay' },
        { gender: gender.Neuter, name: 'Catchacimil' },
        { gender: gender.Neuter, name: 'Koyucu' },
        { gender: gender.Neuter, name: 'Muncay' },
        { gender: gender.Neuter, name: 'Waratil' },
        { gender: gender.Neuter, name: 'Yaracay' },
        { gender: gender.Neuter, name: 'Ikallcu' },
        { gender: gender.Neuter, name: 'Kipil' },
        { gender: gender.Neuter, name: 'Akapatsu' },
        { gender: gender.Neuter, name: 'Cocotay' },
        { gender: gender.Neuter, name: 'Mallmay' },
        { gender: gender.Neuter, name: 'Chakaril' },
        { gender: gender.Neuter, name: 'Soncocayllu' },
        { gender: gender.Neuter, name: 'Cokupay' },
        { gender: gender.Neuter, name: 'Huacanchakay' },
        { gender: gender.Neuter, name: 'Ayahuachay' },
        { gender: gender.Neuter, name: 'Paillytu' },
        { gender: gender.Neuter, name: 'Amachakuncu' },
        { gender: gender.Neuter, name: 'Apanpunil' },
        { gender: gender.Neuter, name: 'Yayatsupu' },
      ]
    },
    get nomenclature() {
      const { minSize, maxSize } = getNameSizeLimits(
        this.names.reduce((acc: string[], curr: Dictionary<string>) => {
          acc.push(curr.name)
          return acc
        }, []),
        'Atlec'
      )
      return {
        nameSize: { min: minSize, max: maxSize },
        specialChars: DEFAULT_SPECIAL_CHARS,
      }
    },
    redirectionLinks: {
      population: 'https://catchaluk.wixsite.com/lejdr/les-atlecs',
      info: true,
    },
  },
  Akoutlal: {
    agglomerationTemplates: {
      City: (n: string) => `${n}'akan`,
      Town: (n: string) => `${n}'tan`,
    },
    criteria: {
      gender: ['Male', 'Female'],
      agglomeration: Object.keys(AGGLOMERATIONS),
    },
    get names() {
      const gender = Object.fromEntries(Object.entries(GENDERS).filter(([k]) => this.criteria.gender.includes(k)))
      return [
        { gender: gender.Female, name: 'Ocimai' },
        { gender: gender.Female, name: 'Eloemi' },
        { gender: gender.Female, name: 'Cachula' },
        { gender: gender.Female, name: 'Pucania' },
        { gender: gender.Female, name: 'Cuenia' },
        { gender: gender.Female, name: 'Mixali' },
        { gender: gender.Female, name: 'Japinia' },
        { gender: gender.Female, name: 'Camaini' },
        { gender: gender.Female, name: 'Piliama' },
        { gender: gender.Female, name: 'Olainia' },
        { gender: gender.Female, name: 'Asacimai' },
        { gender: gender.Female, name: 'Utilachi' },
        { gender: gender.Female, name: 'Pumaspa' },
        { gender: gender.Female, name: 'Tapuya' },
        { gender: gender.Female, name: 'Iwixa' },
        { gender: gender.Female, name: 'Juwari' },
        { gender: gender.Female, name: 'Icinia' },
        { gender: gender.Female, name: 'Purija' },
        { gender: gender.Female, name: 'Manuta' },
        { gender: gender.Female, name: 'Muqania' },
        { gender: gender.Female, name: 'Saxtania' },
        { gender: gender.Female, name: 'Ipania' },
        { gender: gender.Female, name: 'Ulici' },
        { gender: gender.Female, name: 'Apirunia' },
        { gender: gender.Female, name: 'Inamayi' },
        { gender: gender.Female, name: 'Jarania' },
        { gender: gender.Female, name: 'Ulutanta' },
        { gender: gender.Female, name: 'Quchuta' },
        { gender: gender.Female, name: 'Chisiri' },
        { gender: gender.Female, name: 'Yuqalli' },
        { gender: gender.Female, name: 'Naxaruma' },
        { gender: gender.Female, name: 'Carami' },
        { gender: gender.Female, name: 'Chalqi' },
        { gender: gender.Female, name: 'Munania' },
        { gender: gender.Female, name: 'Ichi' },
        { gender: gender.Female, name: 'Waxayani' },
        { gender: gender.Female, name: 'Wilsa' },
        { gender: gender.Female, name: 'Tunaxi' },
        { gender: gender.Female, name: 'Apaninia' },
        { gender: gender.Female, name: 'Ujumari' },
        { gender: gender.Female, name: 'Jipilpa' },
        { gender: gender.Female, name: 'Sillania' },
        { gender: gender.Female, name: 'Tawari' },
        { gender: gender.Female, name: 'Chapili' },
        { gender: gender.Female, name: 'Pilimpa' },
        { gender: gender.Female, name: 'Janchi' },
        { gender: gender.Female, name: 'Tita' },
        { gender: gender.Female, name: 'Arunia' },
        { gender: gender.Female, name: 'Wajili' },
        { gender: gender.Female, name: 'Cachuchi' },
        { gender: gender.Female, name: 'Cutimi' },
        { gender: gender.Female, name: 'Achakiri' },
        { gender: gender.Female, name: 'Jali' },
        { gender: gender.Female, name: 'Chalani' },
        { gender: gender.Female, name: 'Cucuna' },
        { gender: gender.Female, name: 'Pianina' },
        { gender: gender.Female, name: 'Wasiri' },
        { gender: gender.Female, name: 'Paqamusi' },
        { gender: gender.Female, name: 'Chinqini' },
        { gender: gender.Female, name: 'Laqacha' },
        { gender: gender.Female, name: 'Taypipi' },
        { gender: gender.Male, name: 'Atlul' },
        { gender: gender.Male, name: 'Takach' },
        { gender: gender.Male, name: 'Taumal' },
        { gender: gender.Male, name: 'Cauyapa' },
        { gender: gender.Male, name: 'Chichato' },
        { gender: gender.Male, name: 'Pamoto' },
        { gender: gender.Male, name: 'Chotol' },
        { gender: gender.Male, name: 'Piloch' },
        { gender: gender.Male, name: 'Utalamu' },
        { gender: gender.Male, name: 'Pilintol' },
        { gender: gender.Male, name: 'Ochulo' },
        { gender: gender.Male, name: 'Chipaual' },
        { gender: gender.Male, name: 'Aruxal' },
        { gender: gender.Male, name: 'Misupu' },
        { gender: gender.Male, name: 'Wancu' },
        { gender: gender.Male, name: 'Cuntul' },
        { gender: gender.Male, name: 'Usu' },
        { gender: gender.Male, name: 'Qiqal' },
        { gender: gender.Male, name: 'Ayul' },
        { gender: gender.Male, name: 'Juchano' },
        { gender: gender.Male, name: 'Chinci' },
        { gender: gender.Male, name: 'Tipayo' },
        { gender: gender.Male, name: 'Chajo' },
        { gender: gender.Male, name: 'Chacchu' },
        { gender: gender.Male, name: 'Lawti' },
        { gender: gender.Male, name: 'Quijpu' },
        { gender: gender.Male, name: 'Chiqupo' },
        { gender: gender.Male, name: 'Ananatu' },
        { gender: gender.Male, name: 'Qarcho' },
        { gender: gender.Male, name: 'Utunqu' },
        { gender: gender.Male, name: 'Xacayu' },
        { gender: gender.Male, name: 'Tayinchu' },
        { gender: gender.Male, name: 'Yaqal' },
        { gender: gender.Male, name: 'Lupuru' },
        { gender: gender.Male, name: 'Laqanii' },
        { gender: gender.Male, name: 'Pachaku' },
        { gender: gender.Male, name: 'Mayuchu' },
        { gender: gender.Male, name: 'Ayacho' },
        { gender: gender.Male, name: 'Sapiju' },
        { gender: gender.Male, name: 'Michol' },
        { gender: gender.Male, name: 'Lajumu' },
        { gender: gender.Male, name: 'Wilqu' },
        { gender: gender.Male, name: 'Puraxi' },
        { gender: gender.Male, name: 'Wacu' },
        { gender: gender.Male, name: 'Ojinco' },
        { gender: gender.Male, name: 'Phujonio' },
        { gender: gender.Male, name: 'Soponi' },
        { gender: gender.Male, name: 'Jupil' },
        { gender: gender.Male, name: 'Acucol' },
        { gender: gender.Male, name: 'Qhimasil' },
        { gender: gender.Male, name: 'Jopupo' },
        { gender: gender.Male, name: 'Qellapu' },
        { gender: gender.Male, name: 'Yajapiri' },
        { gender: gender.Male, name: 'Pulumo' },
        { gender: gender.Male, name: 'Jichol' },
        { gender: gender.Male, name: 'Tajapachu' },
        { gender: gender.Male, name: 'Satayu' },
        { gender: gender.Male, name: 'Yanapol' },
        { gender: gender.Male, name: 'Tonxi' },
        { gender: gender.Male, name: 'Majuntu' },
        { gender: gender.Male, name: 'Waqantu' },
      ]
    },
    get nomenclature() {
      const { minSize, maxSize } = getNameSizeLimits(
        this.names.reduce((acc: string[], curr: Dictionary<string>) => {
          acc.push(curr.name)
          return acc
        }, []),
        'Akoutlal'
      )
      return {
        nameSize: { min: minSize, max: maxSize },
        specialChars: DEFAULT_SPECIAL_CHARS,
      }
    },
    redirectionLinks: {
      population: 'https://catchaluk.wixsite.com/lejdr/les-akoutlals',
    },
  },
  'Cutchakan&Iktomi': {
    agglomerationTemplates: {
      City: (n: string) => `${n}'itza`,
      Town: (n: string) => `${n}'vul`,
    },
    criteria: {
      gender: ['Male', 'Female', 'Neuter'],
      agglomeration: Object.keys(AGGLOMERATIONS),
    },
    get names() {
      const gender = Object.fromEntries(Object.entries(GENDERS).filter(([k]) => this.criteria.gender.includes(k)))
      return [
        { gender: gender.Female, name: "Ix'kapapi" },
        { gender: gender.Female, name: 'Necahuam' },
        { gender: gender.Female, name: 'Itzama' },
        { gender: gender.Female, name: "Xoca'lam" },
        { gender: gender.Female, name: 'Cacozi' },
        { gender: gender.Female, name: "Metzi'ti" },
        { gender: gender.Female, name: "Acte'pa" },
        { gender: gender.Female, name: "Culek'ix" },
        { gender: gender.Female, name: "Pixa'yikab" },
        { gender: gender.Female, name: 'Ciczamla' },
        { gender: gender.Female, name: "Nen'kanab" },
        { gender: gender.Female, name: "Ix'cabab" },
        { gender: gender.Female, name: "Letil'ma" },
        { gender: gender.Female, name: "Acuxa'nab" },
        { gender: gender.Female, name: 'Bactam' },
        { gender: gender.Female, name: "Ukab'ab" },
        { gender: gender.Female, name: "Ab'baci" },
        { gender: gender.Female, name: "Bech'am" },
        { gender: gender.Female, name: "Bibil'ab" },
        { gender: gender.Female, name: "Cel'ibi" },
        { gender: gender.Female, name: "Kotjaca'nam" },
        { gender: gender.Female, name: "Lelix'amam" },
        { gender: gender.Female, name: "Ch'camam" },
        { gender: gender.Female, name: 'Eram' },
        { gender: gender.Female, name: 'Ilanab' },
        { gender: gender.Female, name: 'Pilola' },
        { gender: gender.Female, name: "Ix'cubab" },
        { gender: gender.Female, name: "Iba'caxi" },
        { gender: gender.Female, name: "Uje'ilab" },
        { gender: gender.Female, name: "Menju'ba" },
        { gender: gender.Female, name: "U'jini" },
        { gender: gender.Female, name: "Lijan'cab" },
        { gender: gender.Female, name: 'Umiti' },
        { gender: gender.Female, name: "Lumu'tab" },
        { gender: gender.Female, name: "Lej'ibi" },
        { gender: gender.Female, name: "Xsewa'tsam" },
        { gender: gender.Female, name: "Chicun'cab" },
        { gender: gender.Female, name: 'Wojoti' },
        { gender: gender.Female, name: "Ix'mucab" },
        { gender: gender.Female, name: "Cuy'kila" },
        { gender: gender.Female, name: 'Calibab' },
        { gender: gender.Female, name: "Niaj'ab" },
        { gender: gender.Female, name: 'Nacali' },
        { gender: gender.Female, name: "Woja'tili" },
        { gender: gender.Female, name: "Ic'abam" },
        { gender: gender.Female, name: "Oki'tchama" },
        { gender: gender.Female, name: "Unicab'a" },
        { gender: gender.Female, name: 'Pewima' },
        { gender: gender.Female, name: "Bacu'tam" },
        { gender: gender.Female, name: "Pichc'ami" },
        { gender: gender.Female, name: "Ixa'cam" },
        { gender: gender.Female, name: "Tzi'manab" },
        { gender: gender.Female, name: 'Petajab' },
        { gender: gender.Female, name: "Cha'katji" },
        { gender: gender.Female, name: 'Chinowi' },
        { gender: gender.Female, name: 'Elesab' },
        { gender: gender.Female, name: "Esan'ika" },
        { gender: gender.Female, name: "Juchun'bam" },
        { gender: gender.Female, name: "Axti'lab" },
        { gender: gender.Female, name: "Jobal'am" },
        { gender: gender.Female, name: "Kab'ukam" },
        { gender: gender.Male, name: "Ocha'Kan" },
        { gender: gender.Male, name: 'Ucub' },
        { gender: gender.Male, name: 'Kakucen' },
        { gender: gender.Male, name: "Zaotz'ike" },
        { gender: gender.Male, name: "Mulac'hun" },
        { gender: gender.Male, name: 'Chaacai' },
        { gender: gender.Male, name: "Bolon'tepe" },
        { gender: gender.Male, name: 'Ukunmatun' },
        { gender: gender.Male, name: "Nal'iktan" },
        { gender: gender.Male, name: "Coyo'zul" },
        { gender: gender.Male, name: "Chicun'can" },
        { gender: gender.Male, name: "Och'tunub" },
        { gender: gender.Male, name: "A'chun" },
        { gender: gender.Male, name: "Baja'hun" },
        { gender: gender.Male, name: "Balul'ai" },
        { gender: gender.Male, name: 'Wabiten' },
        { gender: gender.Male, name: "Caboul'chun" },
        { gender: gender.Male, name: "Oc'jemen" },
        { gender: gender.Male, name: "Catanin'hub" },
        { gender: gender.Male, name: 'Chacatun' },
        { gender: gender.Male, name: 'Tecletun' },
        { gender: gender.Male, name: "Ichiji'cen" },
        { gender: gender.Male, name: 'Umun' },
        { gender: gender.Male, name: "Jaca'tan" },
        { gender: gender.Male, name: "Weju'bun" },
        { gender: gender.Male, name: 'Jetai' },
        { gender: gender.Male, name: "Puma'jilun" },
        { gender: gender.Male, name: "Jol'chun" },
        { gender: gender.Male, name: "Cchoc'can" },
        { gender: gender.Male, name: "Oloc'jub" },
        { gender: gender.Male, name: "Macun'cub" },
        { gender: gender.Male, name: 'Ajaken' },
        { gender: gender.Male, name: "Inchu'jiben" },
        { gender: gender.Male, name: 'Muruxun' },
        { gender: gender.Male, name: "Uyul'tun" },
        { gender: gender.Male, name: "Nachi'bun" },
        { gender: gender.Male, name: "Nun'tebe" },
        { gender: gender.Male, name: "Ochol'e" },
        { gender: gender.Male, name: "Pomun'kub" },
        { gender: gender.Male, name: "Pet'zun" },
        { gender: gender.Male, name: "Ju'bete" },
        { gender: gender.Male, name: "Petem'tub" },
        { gender: gender.Male, name: "Puch'ube" },
        { gender: gender.Male, name: 'Obalun' },
        { gender: gender.Male, name: "Chob'un" },
        { gender: gender.Male, name: "Pun'unub" },
        { gender: gender.Male, name: 'Chocolen' },
        { gender: gender.Male, name: "Uzu'ben" },
        { gender: gender.Male, name: "Bala'pen" },
        { gender: gender.Male, name: "Upun'cub" },
        { gender: gender.Male, name: "Paju'lepe" },
        { gender: gender.Male, name: "Aja'wape" },
        { gender: gender.Male, name: 'Chelabun' },
        { gender: gender.Male, name: "Iba'iten" },
        { gender: gender.Male, name: "Jenaji'can" },
        { gender: gender.Male, name: "Saran'kub" },
        { gender: gender.Male, name: "Baja'capan" },
        { gender: gender.Male, name: "Bon'muchub" },
        { gender: gender.Male, name: 'Jomajun' },
        { gender: gender.Male, name: "Achayi'bun" },
        { gender: gender.Male, name: 'Eyawakun' },
        { gender: gender.Neuter, name: "Yok'tzan" },
        { gender: gender.Neuter, name: "Acha'pai" },
        { gender: gender.Neuter, name: "Xama'pai" },
        { gender: gender.Neuter, name: "Ajap'Amai" },
        { gender: gender.Neuter, name: "Cara'jil" },
        { gender: gender.Neuter, name: 'Yomil' },
        { gender: gender.Neuter, name: 'Axija' },
        { gender: gender.Neuter, name: "Uyakun'kan" },
        { gender: gender.Neuter, name: "Bal'il" },
        { gender: gender.Neuter, name: "Xoboli'lan" },
        { gender: gender.Neuter, name: "Cojuli'cai" },
        { gender: gender.Neuter, name: 'Cochibil' },
        { gender: gender.Neuter, name: "Cuju'aban" },
        { gender: gender.Neuter, name: "Ajte'il" },
        { gender: gender.Neuter, name: "Ajni'bil" },
        { gender: gender.Neuter, name: "Oxib'ana" },
        { gender: gender.Neuter, name: "Colja'nil" },
        { gender: gender.Neuter, name: 'Ajimay' },
        { gender: gender.Neuter, name: "Echem'ma" },
        { gender: gender.Neuter, name: "Jupu'ma" },
        { gender: gender.Neuter, name: "Machti'kil" },
        { gender: gender.Neuter, name: "Ikal'il" },
        { gender: gender.Neuter, name: 'Laca' },
        { gender: gender.Neuter, name: "Umbal'an" },
        { gender: gender.Neuter, name: "Ancho'jibil" },
        { gender: gender.Neuter, name: "Matan'tan" },
        { gender: gender.Neuter, name: "Michi'kai" },
        { gender: gender.Neuter, name: "Aka'mil" },
        { gender: gender.Neuter, name: "Mulip'an" },
        { gender: gender.Neuter, name: 'Chumtil' },
        { gender: gender.Neuter, name: "Ic'cancai" },
        { gender: gender.Neuter, name: "Oc'chil" },
        { gender: gender.Neuter, name: 'Pumil' },
        { gender: gender.Neuter, name: "An'anchil" },
        { gender: gender.Neuter, name: "Ani'kubil" },
        { gender: gender.Neuter, name: "Pumji'ban" },
        { gender: gender.Neuter, name: 'Uyuba' },
        { gender: gender.Neuter, name: "Paca'til" },
        { gender: gender.Neuter, name: "Octo'pai" },
        { gender: gender.Neuter, name: "Ulun'pai" },
        { gender: gender.Neuter, name: 'Jetema' },
        { gender: gender.Neuter, name: "Pom'pan" },
        { gender: gender.Neuter, name: "Pora'jil" },
        { gender: gender.Neuter, name: "Puy'pa" },
        { gender: gender.Neuter, name: "Un'til" },
        { gender: gender.Neuter, name: "Cajan'pil" },
        { gender: gender.Neuter, name: "Al'cumpa" },
        { gender: gender.Neuter, name: "Zucan'apai" },
        { gender: gender.Neuter, name: "Bula'cai" },
        { gender: gender.Neuter, name: "Chu'chan" },
        { gender: gender.Neuter, name: "Tal'ucan" },
        { gender: gender.Neuter, name: "Ak'panan" },
        { gender: gender.Neuter, name: "Cha'xopan" },
        { gender: gender.Neuter, name: 'Ijuyil' },
        { gender: gender.Neuter, name: 'Chuluja' },
        { gender: gender.Neuter, name: "Ika'ijil" },
        { gender: gender.Neuter, name: "Imuch'til" },
        { gender: gender.Neuter, name: 'Itzelai' },
        { gender: gender.Neuter, name: 'Jewatan' },
        { gender: gender.Neuter, name: "Maja'pila" },
        { gender: gender.Neuter, name: "Ma'atan" },
      ]
    },
    get nomenclature() {
      const { minSize, maxSize } = getNameSizeLimits(
        this.names.reduce((acc: string[], curr: Dictionary<string>) => {
          acc.push(curr.name)
          return acc
        }, []),
        'Cutchakan&Iktomi'
      )
      return {
        nameSize: { min: minSize, max: maxSize },
        specialChars: DEFAULT_SPECIAL_CHARS,
      }
    },
    redirectionLinks: {
      population: [
        'https://catchaluk.wixsite.com/lejdr/les-cutchakans',
        'https://catchaluk.wixsite.com/lejdr/les-iktomis',
      ],
      info: true,
    },
  },
  Oxotlli: {
    agglomerationTemplates: {
      City: (n: string) => `${n}'ixitan`,
      Town: (n: string) => `${n}'itan`,
    },
    criteria: {
      gender: ['Male', 'Female'],
      agglomeration: Object.keys(AGGLOMERATIONS),
    },
    get names() {
      const gender = Object.fromEntries(Object.entries(GENDERS).filter(([k]) => this.criteria.gender.includes(k)))
      return [
        { gender: gender.Female, name: "Panat'a" },
        { gender: gender.Female, name: 'Nojika' },
        { gender: gender.Female, name: "T'ipaawa" },
        { gender: gender.Female, name: "T'omoc" },
        { gender: gender.Female, name: 'Chiwatel' },
        { gender: gender.Female, name: 'Ilika' },
        { gender: gender.Female, name: 'Panina' },
        { gender: gender.Female, name: "Nat'ukel" },
        { gender: gender.Female, name: 'Muyunoc' },
        { gender: gender.Female, name: 'Mapachoc' },
        { gender: gender.Female, name: 'Citali' },
        { gender: gender.Female, name: 'Itoloc' },
        { gender: gender.Female, name: "Et'onel" },
        { gender: gender.Female, name: "T'ilapaa" },
        { gender: gender.Female, name: 'Apaalu' },
        { gender: gender.Female, name: 'Alika' },
        { gender: gender.Female, name: 'Iwinoc' },
        { gender: gender.Female, name: 'Tiinema' },
        { gender: gender.Female, name: 'Olobek' },
        { gender: gender.Female, name: "Ucut'oc" },
        { gender: gender.Female, name: 'Chapota' },
        { gender: gender.Female, name: 'Palatocaa' },
        { gender: gender.Female, name: 'Jamak' },
        { gender: gender.Female, name: "T'iconoc" },
        { gender: gender.Female, name: 'Wojoc' },
        { gender: gender.Female, name: "Chuwat'a" },
        { gender: gender.Female, name: 'Arimec' },
        { gender: gender.Female, name: 'Ekama' },
        { gender: gender.Female, name: 'Opinaa' },
        { gender: gender.Female, name: 'Iloca' },
        { gender: gender.Female, name: "Tint'a" },
        { gender: gender.Female, name: 'Lililpoc' },
        { gender: gender.Female, name: 'Eyatoc' },
        { gender: gender.Female, name: "At'oc" },
        { gender: gender.Female, name: 'Itzeel' },
        { gender: gender.Female, name: 'Acoja' },
        { gender: gender.Female, name: 'Pkaamel' },
        { gender: gender.Female, name: 'Azetoc' },
        { gender: gender.Female, name: 'Jewapel' },
        { gender: gender.Female, name: 'Uropaa' },
        { gender: gender.Female, name: 'Aliichoc' },
        { gender: gender.Female, name: 'kicel' },
        { gender: gender.Female, name: 'Awebaala' },
        { gender: gender.Female, name: "Elot'oc" },
        { gender: gender.Female, name: 'Kocoja' },
        { gender: gender.Female, name: 'Banboc' },
        { gender: gender.Female, name: 'Setomel' },
        { gender: gender.Female, name: "Oolot'a" },
        { gender: gender.Female, name: 'Lajuuna' },
        { gender: gender.Female, name: 'Linta' },
        { gender: gender.Female, name: 'Makowa' },
        { gender: gender.Female, name: "Joot'a" },
        { gender: gender.Female, name: "T'ebel" },
        { gender: gender.Female, name: 'Sujitel' },
        { gender: gender.Female, name: "T'ot'otesa" },
        { gender: gender.Female, name: 'Yalobel' },
        { gender: gender.Female, name: 'Jalumaa' },
        { gender: gender.Female, name: 'Sinana' },
        { gender: gender.Female, name: "T'icolel" },
        { gender: gender.Female, name: 'Petsena' },
        { gender: gender.Female, name: 'Calenok' },
        { gender: gender.Male, name: "At'apan" },
        { gender: gender.Male, name: 'Utaji' },
        { gender: gender.Male, name: 'Ojoli' },
        { gender: gender.Male, name: 'Towati' },
        { gender: gender.Male, name: 'Nimaali' },
        { gender: gender.Male, name: "Ut'umati" },
        { gender: gender.Male, name: 'Pomatep' },
        { gender: gender.Male, name: 'Unecep' },
        { gender: gender.Male, name: 'Bacilcan' },
        { gender: gender.Male, name: "Wit'epec" },
        { gender: gender.Male, name: 'Nabuuli' },
        { gender: gender.Male, name: 'Ujaaki' },
        { gender: gender.Male, name: "It'atep" },
        { gender: gender.Male, name: "Balt'ii" },
        { gender: gender.Male, name: 'Usunep' },
        { gender: gender.Male, name: 'Yomi' },
        { gender: gender.Male, name: "At'inik" },
        { gender: gender.Male, name: 'Chichep' },
        { gender: gender.Male, name: 'Banuc' },
        { gender: gender.Male, name: 'Utinti' },
        { gender: gender.Male, name: "Chat'i" },
        { gender: gender.Male, name: 'Achep' },
        { gender: gender.Male, name: 'Jujuni' },
        { gender: gender.Male, name: 'Esaji' },
        { gender: gender.Male, name: 'Abalep' },
        { gender: gender.Male, name: 'Ypejep' },
        { gender: gender.Male, name: "Abat'i" },
        { gender: gender.Male, name: "Et'etii" },
        { gender: gender.Male, name: 'Bilki' },
        { gender: gender.Male, name: "T'awapi" },
        { gender: gender.Male, name: 'Akaani' },
        { gender: gender.Male, name: "Bet'ep" },
        { gender: gender.Male, name: 'Jobali' },
        { gender: gender.Male, name: "It'imali" },
        { gender: gender.Male, name: 'Akuti' },
        { gender: gender.Male, name: 'Jetep' },
        { gender: gender.Male, name: 'Etuumep' },
        { gender: gender.Male, name: 'Ilici' },
        { gender: gender.Male, name: 'Jok' },
        { gender: gender.Male, name: "Mulet'ep" },
        { gender: gender.Male, name: 'Aniinaci' },
        { gender: gender.Male, name: 'Yukep' },
        { gender: gender.Male, name: 'Paculi' },
        { gender: gender.Male, name: 'Ijik' },
        { gender: gender.Male, name: "Oomit'i" },
        { gender: gender.Male, name: "Poot'i" },
        { gender: gender.Male, name: 'Watii' },
        { gender: gender.Male, name: 'Kilci' },
        { gender: gender.Male, name: 'Locokep' },
        { gender: gender.Male, name: 'Malaki' },
        { gender: gender.Male, name: 'Noti' },
        { gender: gender.Male, name: "Iket'oc" },
        { gender: gender.Male, name: "Tet'epi" },
        { gender: gender.Male, name: 'Jajipi' },
        { gender: gender.Male, name: 'Chubuc' },
        { gender: gender.Male, name: 'Yaalotep' },
        { gender: gender.Male, name: "T'ajili" },
        { gender: gender.Male, name: 'Nakanimi' },
        { gender: gender.Male, name: "Wut'ijep" },
        { gender: gender.Male, name: 'Kupini' },
        { gender: gender.Male, name: 'Julonic' },
      ]
    },
    get nomenclature() {
      const { minSize, maxSize } = getNameSizeLimits(
        this.names.reduce((acc: string[], curr: Dictionary<string>) => {
          acc.push(curr.name)
          return acc
        }, []),
        'Oxotlli'
      )
      const specialChars = objectDeepEnoughCopy(DEFAULT_SPECIAL_CHARS)
      specialChars[APOSTROPHE_CHAR].isException = (name: string, charIndex: number) =>
        name[charIndex - 1] && name[charIndex - 1].toLowerCase() === 't'
      return {
        nameSize: { min: minSize, max: maxSize },
        specialChars,
      }
    },
    redirectionLinks: {
      population: 'https://catchaluk.wixsite.com/lejdr/les-oxotllis',
      info: true,
    },
  },
  Tigui: {
    agglomerationTemplates: {
      City: (n: string) => `waete-${n}`,
      Town: (n: string) => `nae-${n}`,
    },
    criteria: {
      gender: ['Male', 'Female'],
      agglomeration: Object.keys(AGGLOMERATIONS),
    },
    get names() {
      const gender = Object.fromEntries(Object.entries(GENDERS).filter(([k]) => this.criteria.gender.includes(k)))
      return [
        { gender: gender.Female, name: 'Aeue' },
        { gender: gender.Female, name: 'Auoni' },
        { gender: gender.Female, name: 'Vaani' },
        { gender: gender.Female, name: 'Alaipi' },
        { gender: gender.Female, name: 'Alienetli' },
        { gender: gender.Female, name: 'Chiacaale' },
        { gender: gender.Female, name: 'Euepa' },
        { gender: gender.Female, name: 'Laoaba' },
        { gender: gender.Female, name: 'Itaale' },
        { gender: gender.Female, name: 'Vamanali' },
        { gender: gender.Female, name: 'Oematli' },
        { gender: gender.Female, name: 'Iuatinatli' },
        { gender: gender.Female, name: 'Pouoca' },
        { gender: gender.Female, name: 'Eionaba' },
        { gender: gender.Female, name: 'Cabaeti' },
        { gender: gender.Female, name: 'Labaani' },
        { gender: gender.Female, name: 'Caobali' },
        { gender: gender.Female, name: 'Maeboua' },
        { gender: gender.Female, name: 'Viciira' },
        { gender: gender.Female, name: 'Bualita' },
        { gender: gender.Female, name: 'Bouiuca' },
        { gender: gender.Female, name: 'Cacouatli' },
        { gender: gender.Female, name: 'Aloui' },
        { gender: gender.Female, name: 'Cimunua' },
        { gender: gender.Female, name: 'Ceili' },
        { gender: gender.Female, name: 'Nachouere' },
        { gender: gender.Female, name: 'Carebi' },
        { gender: gender.Female, name: 'Ulaiele' },
        { gender: gender.Female, name: 'Chinuamai' },
        { gender: gender.Female, name: 'Iaroani' },
        { gender: gender.Female, name: 'Neagunoi' },
        { gender: gender.Female, name: 'Aiuotli' },
        { gender: gender.Female, name: 'Eataaca' },
        { gender: gender.Female, name: 'Ataalima' },
        { gender: gender.Female, name: 'Ateutli' },
        { gender: gender.Female, name: 'Eyaoma' },
        { gender: gender.Female, name: 'Baaibatli' },
        { gender: gender.Female, name: 'Leuemi' },
        { gender: gender.Female, name: 'Baaochatli' },
        { gender: gender.Female, name: 'Naemeti' },
        { gender: gender.Female, name: 'Uleuai' },
        { gender: gender.Female, name: 'Nuacuwaali' },
        { gender: gender.Female, name: 'Vuaatli' },
        { gender: gender.Female, name: 'Vapaalai' },
        { gender: gender.Female, name: 'Pouana' },
        { gender: gender.Female, name: 'Manaoa' },
        { gender: gender.Female, name: 'Caetoali' },
        { gender: gender.Female, name: 'Naucoami' },
        { gender: gender.Female, name: 'Caevaatli' },
        { gender: gender.Female, name: 'Ueluli' },
        { gender: gender.Female, name: 'Nutaete' },
        { gender: gender.Female, name: 'Taavoeni' },
        { gender: gender.Female, name: 'Aeloitli' },
        { gender: gender.Female, name: 'Nouaba' },
        { gender: gender.Female, name: 'Camaobe' },
        { gender: gender.Female, name: 'Liamaipi' },
        { gender: gender.Female, name: 'Maenaba' },
        { gender: gender.Female, name: 'Ucuava' },
        { gender: gender.Female, name: 'Abaatoni' },
        { gender: gender.Female, name: 'Ocoatli' },
        { gender: gender.Female, name: 'Niuiti' },
        { gender: gender.Male, name: 'Amakua' },
        { gender: gender.Male, name: 'Macoa' },
        { gender: gender.Male, name: 'Tuenibara' },
        { gender: gender.Male, name: 'Avulu' },
        { gender: gender.Male, name: 'Pacanea' },
        { gender: gender.Male, name: 'Amaotu' },
        { gender: gender.Male, name: 'Caolete' },
        { gender: gender.Male, name: 'Eugouta' },
        { gender: gender.Male, name: 'Caometle' },
        { gender: gender.Male, name: 'Noadape' },
        { gender: gender.Male, name: 'Amonotle' },
        { gender: gender.Male, name: 'Loumaca' },
        { gender: gender.Male, name: 'Aeketul' },
        { gender: gender.Male, name: 'Ganiana' },
        { gender: gender.Male, name: 'Ahualu' },
        { gender: gender.Male, name: 'Abaacu' },
        { gender: gender.Male, name: 'Bapatoue' },
        { gender: gender.Male, name: 'Abaioca' },
        { gender: gender.Male, name: 'Veleobe' },
        { gender: gender.Male, name: 'Vaouli' },
        { gender: gender.Male, name: 'Aietobou' },
        { gender: gender.Male, name: 'Caambacu' },
        { gender: gender.Male, name: 'Wetaca' },
        { gender: gender.Male, name: 'Leenacoie' },
        { gender: gender.Male, name: 'Tigooneme' },
        { gender: gender.Male, name: 'Cemenuele' },
        { gender: gender.Male, name: 'Iaculaua' },
        { gender: gender.Male, name: 'Auimee' },
        { gender: gender.Male, name: 'Acuapa' },
        { gender: gender.Male, name: 'Kaatatu' },
        { gender: gender.Male, name: 'Taereme' },
        { gender: gender.Male, name: 'Vaalau' },
        { gender: gender.Male, name: 'Amaalau' },
        { gender: gender.Male, name: 'Caubuche' },
        { gender: gender.Male, name: 'Beeuba' },
        { gender: gender.Male, name: 'Neamau' },
        { gender: gender.Male, name: 'Noebale' },
        { gender: gender.Male, name: 'Caoiae' },
        { gender: gender.Male, name: 'Caiepitan' },
        { gender: gender.Male, name: 'Booma' },
        { gender: gender.Male, name: 'Acaamie' },
        { gender: gender.Male, name: 'Penuama' },
        { gender: gender.Male, name: 'Maiaatu' },
        { gender: gender.Male, name: 'Ueachae' },
        { gender: gender.Male, name: 'Chuevetu' },
        { gender: gender.Male, name: 'Coaca' },
        { gender: gender.Male, name: 'Cuanaeme' },
        { gender: gender.Male, name: 'Eveunu' },
        { gender: gender.Male, name: 'Coavaatu' },
        { gender: gender.Male, name: 'Auewa' },
        { gender: gender.Male, name: 'Paaneatu' },
        { gender: gender.Male, name: 'Paelau' },
        { gender: gender.Male, name: 'Naapate' },
        { gender: gender.Male, name: 'Uaitucu' },
        { gender: gender.Male, name: 'Touaboke' },
        { gender: gender.Male, name: 'Oibime' },
        { gender: gender.Male, name: 'Ocavaalue' },
        { gender: gender.Male, name: 'Uanuma' },
        { gender: gender.Male, name: 'Neouetu' },
        { gender: gender.Male, name: 'Catamale' },
        { gender: gender.Male, name: 'Neuvoa' },
      ]
    },
    get nomenclature() {
      const { minSize, maxSize } = getNameSizeLimits(
        this.names.reduce((acc: string[], curr: Dictionary<string>) => {
          acc.push(curr.name)
          return acc
        }, []),
        'Tigui'
      )
      return {
        nameSize: { min: minSize, max: maxSize },
        specialChars: DEFAULT_SPECIAL_CHARS,
      }
    },
    redirectionLinks: {
      population: 'https://catchaluk.wixsite.com/lejdr/les-tiguis',
    },
  },
  Tucoya: {
    agglomerationTemplates: {
      City: (n: string) => `${n}'sikotsutsu`,
      Town: (n: string) => `${n}'sikotsu`,
    },
    criteria: {
      gender: ['Neuter'],
      agglomeration: Object.keys(AGGLOMERATIONS),
    },
    get names() {
      const gender = Object.fromEntries(Object.entries(GENDERS).filter(([k]) => this.criteria.gender.includes(k)))
      return [
        { gender: gender.Neuter, name: 'Cacoya' },
        { gender: gender.Neuter, name: 'Yeyani' },
        { gender: gender.Neuter, name: 'Cainaco' },
        { gender: gender.Neuter, name: 'Ciricacu' },
        { gender: gender.Neuter, name: 'Camena' },
        { gender: gender.Neuter, name: 'Locoda' },
        { gender: gender.Neuter, name: 'Receconi' },
        { gender: gender.Neuter, name: 'Malece' },
        { gender: gender.Neuter, name: 'Arinra' },
        { gender: gender.Neuter, name: 'Cemici' },
        { gender: gender.Neuter, name: 'Dicope' },
        { gender: gender.Neuter, name: 'Diducudun' },
        { gender: gender.Neuter, name: 'Tsitinicu' },
        { gender: gender.Neuter, name: 'Madunu' },
        { gender: gender.Neuter, name: 'Bokotsime' },
        { gender: gender.Neuter, name: 'Pakanate' },
        { gender: gender.Neuter, name: 'Saratun' },
        { gender: gender.Neuter, name: 'Iabutuni' },
        { gender: gender.Neuter, name: 'Abadoni' },
        { gender: gender.Neuter, name: 'Usanotsi' },
        { gender: gender.Neuter, name: 'Totadun' },
        { gender: gender.Neuter, name: 'Monopuni' },
        { gender: gender.Neuter, name: 'Cafobete' },
        { gender: gender.Neuter, name: 'Muyayani' },
        { gender: gender.Neuter, name: 'Inabo' },
        { gender: gender.Neuter, name: 'Totsadun' },
        { gender: gender.Neuter, name: 'Cosanani' },
        { gender: gender.Neuter, name: 'Cotaba' },
        { gender: gender.Neuter, name: 'Imatoca' },
        { gender: gender.Neuter, name: 'Abutade' },
        { gender: gender.Neuter, name: 'Aimatina' },
        { gender: gender.Neuter, name: 'Maritini' },
        { gender: gender.Neuter, name: 'Metesi' },
        { gender: gender.Neuter, name: 'Casaloni' },
        { gender: gender.Neuter, name: 'Docetini' },
        { gender: gender.Neuter, name: 'Uyubadun' },
        { gender: gender.Neuter, name: 'Udutsuce' },
        { gender: gender.Neuter, name: 'Matutsi' },
        { gender: gender.Neuter, name: 'Paronuri' },
        { gender: gender.Neuter, name: 'Comotuni' },
        { gender: gender.Neuter, name: 'Locene' },
        { gender: gender.Neuter, name: 'Cicaba' },
        { gender: gender.Neuter, name: 'Doconi' },
        { gender: gender.Neuter, name: 'Yopoye' },
        { gender: gender.Neuter, name: 'Miratun' },
        { gender: gender.Neuter, name: 'Catsada' },
        { gender: gender.Neuter, name: 'Etseto' },
        { gender: gender.Neuter, name: 'Alecebe' },
        { gender: gender.Neuter, name: 'Motsidi' },
        { gender: gender.Neuter, name: 'Parudun' },
        { gender: gender.Neuter, name: 'Tsutuya' },
        { gender: gender.Neuter, name: 'Mabayo' },
        { gender: gender.Neuter, name: 'Bicido' },
        { gender: gender.Neuter, name: 'Irotun' },
        { gender: gender.Neuter, name: 'Dena' },
        { gender: gender.Neuter, name: 'Uniaco' },
        { gender: gender.Neuter, name: 'Inadun' },
        { gender: gender.Neuter, name: 'Aiarun' },
        { gender: gender.Neuter, name: 'Codibitsi' },
        { gender: gender.Neuter, name: 'Maicadune' },
        { gender: gender.Neuter, name: 'Bamina' },
      ]
    },
    get nomenclature() {
      const { minSize, maxSize } = getNameSizeLimits(
        this.names.reduce((acc: string[], curr: Dictionary<string>) => {
          acc.push(curr.name)
          return acc
        }, []),
        'Tucoya'
      )
      return {
        nameSize: { min: minSize, max: maxSize },
        specialChars: DEFAULT_SPECIAL_CHARS,
      }
    },
    redirectionLinks: {
      population: 'https://catchaluk.wixsite.com/lejdr/les-tucoyas',
      info: true,
    },
  },
}

const PopulationBase = Object.fromEntries(
  Object.entries(rawPopulationBase).sort((popA, popB) => (popA[0] < popB[0] ? -1 : 1))
)

Object.entries(PopulationBase).forEach(([popName, PopulationData]) => {
  const formattedNames = PopulationData.names.reduce((acc: PopulationName, curr: Dictionary<string>) => {
    const formattedName = curr.name.replace(/-/g, '‑') // hyphen -> unbreakable hyphen
    acc.push({ gender: curr.gender, name: formattedName })
    return acc
  }, [])
  // @ts-expect-error
  delete PopulationBase[popName].names
  PopulationBase[popName].names = formattedNames
})

export { PopulationBase }
